oir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tests/', include('test_data.urls')),
    path('', RedirectView.as_view(url='/tests'), name='go-to-tests'),
]

test_data/urls.py
from django.urls import path
from . import views

app_name = 'test_data'

urlpatterns = [
    path('', views.tests_list, name='test_list'),
    path('running/<test_id>', views.tests_running, name='test_running'),
    path('success', views.success_page, name='success_page'),
    path('dashboard', views.dashboard_main, name='dashboard_main'),
    path('dashboard/tests/<test_id>', views.dashboard_test_result, name='dashboard_test_result'),
    path('dashboard/tests/<test_id>/charts', views.dashboard_test_charts, name='dashboard_test_charts'),
    path('dashboard/tests/<test_id>/full', views.dashboard_test_full, name='dashboard_test_full'),
]

test_data/models.py
from django.db import models


SINGLE = 1
MULTIPLE = 2
TEXT = 3

QUESTION_TYPE_CHOICES = (
    (SINGLE, 'Single (radio)'),
    (MULTIPLE, 'Multiple (checkbox)'),
    (TEXT, 'Text field'),
)


class EmployeeKind(models.Model):
    employee_kind = models.CharField(verbose_name="Вид сотрудника", max_length=255)

    def __str__(self):
        return self.employee_kind

    class Meta:
        ordering = ('id',)
        verbose_name = 'EmployeeKind'
        verbose_name_plural = 'EmployeeKinds'


class Subdivision(models.Model):
    subdivision_name = models.CharField(verbose_name="Название подразделения", max_length=255)

    def __str__(self):
        return self.subdivision_name

    class Meta:
        ordering = ('id',)
        verbose_name = 'Subdivision'
        verbose_name_plural = 'Subdivisions'


class Faculty(models.Model):
    faculty_name = models.CharField(verbose_name="Название факультета", max_length=255)

    def __str__(self):
        return self.faculty_name

    class Meta:
        ordering = ('id',)
        verbose_name = 'Faculty'
        verbose_name_plural = 'Faculties'


class Course(models.Model):
    course_name = models.CharField(verbose_name="Курс", max_length=255)

    def __str__(self):
        return self.course_name

    class Meta:
        ordering = ('id',)
        verbose_name = 'Course'
        verbose_name_plural = 'Courses'


class TestData(models.Model):
    test_name = models.CharField(verbose_name="Название теста", max_length=255)
    extra_data = models.TextField(verbose_name="Дополнительная информация", blank=True, null=True)
    data_created = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)

    def __str__(self):
        return self.test_name

    class Meta:
        ordering = ('id',)
        verbose_name = 'TestData'
        verbose_name_plural = '1 TestsData'


class QuestionaryData(models.Model):
    test = models.ForeignKey(TestData, verbose_name="Тест", on_delete=models.CASCADE, blank=True, null=True)
    employee_kind = models.ForeignKey(EmployeeKind, verbose_name="Тип сотрудника", on_delete=models.CASCADE)
    subdivision = models.ForeignKey(Subdivision, on_delete=models.CASCADE, verbose_name="Подразделение", blank=True,
                                    null=True)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE, verbose_name="Факультет", blank=True,
                                null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="Курс", blank=True,
                               null=True)

    def __str__(self):
        return self.employee_kind.employee_kind

    class Meta:
        ordering = ('id',)
        verbose_name = 'QuestionaryData'
        verbose_name_plural = 'QuestionaryData'


class Question(models.Model):
    question_type = models.IntegerField(verbose_name="Тип вопроса", choices=QUESTION_TYPE_CHOICES, default=SINGLE)
    test_data = models.ForeignKey(TestData, on_delete=models.CASCADE, verbose_name="Тест")
    question_text = models.CharField(verbose_name="Текст вопроса", max_length=255)
    index_number = models.IntegerField(verbose_name="Порядковый номер вопроса", blank=True, null=True)

    def __str__(self):
        return self.question_text + ' ' + str(self.question_type)

    class Meta:
        ordering = ('index_number',)
        verbose_name = 'Question'
        verbose_name_plural = '2 Questions'


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name="Вопрос")
    answer_text = models.CharField(verbose_name="Текст ответа", max_length=255)
    has_extra_data = models.BooleanField(verbose_name="Имеет дополнительную информацию", default=False)
    index_number = models.IntegerField(verbose_name="Порядковый номер ответа", blank=True, null=True)

    def __str__(self):
        return self.answer_text

    class Meta:
        ordering = ('id',)
        verbose_name = 'Answer'
        verbose_name_plural = '3 Answers'


class TestResult(models.Model):
    questionary_data = models.ForeignKey(QuestionaryData, on_delete=models.CASCADE, verbose_name="Данные анкеты")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name="Вопрос")
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, verbose_name="Ответ", blank=True, null=True)
    answer_text = models.TextField(verbose_name="Ответ (текстовый)", blank=True, null=True)
    extra_data = models.TextField(verbose_name="Дополнительная информация к ответу", blank=True, null=True)

    def __str__(self):
        return self.questionary_data.employee_kind.employee_kind + ' ' + self.question.question_text

    class Meta:
        ordering = ('id',)
        verbose_name = 'TestResult'
        verbose_name_plural = '4 TestResults'

test_data/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from .models import TestData, Subdivision, Faculty, Course, QuestionaryData, EmployeeKind, TestResult, Answer
from .models import SINGLE, MULTIPLE, TEXT
from django.db import transaction
from django.http import HttpResponse

EMPLOYEE_CADET_ID = 1
EMPLOYEE_PPS_ID = 2


def tests_list(request):
    if request.user_agent.browser.family == 'IE':
        return HttpResponse("Ваш браузер не поддерживается")
    else:
        all_tests_list = TestData.objects.all()
        return render(request, 'test_data/test_list.html', {'all_tests_list': all_tests_list})


@transaction.atomic
def tests_running(request, test_id):
    if request.method == "POST":
        employee_kind = get_object_or_404(EmployeeKind, pk=request.POST['employee_kind'])
        subdivision = get_object_or_404(Subdivision,
                                        pk=request.POST['subdivision']) if 'subdivision' in request.POST and \
                                                                           request.POST['subdivision'] != '' else None
        faculty = get_object_or_404(Faculty, pk=request.POST['faculty']) if 'faculty' in request.POST and request.POST[
            'faculty'] != '' else None
        course = get_object_or_404(Course, pk=request.POST['course']) if 'course' in request.POST and request.POST[
            'course'] != '' else None

        new_questionary_data = QuestionaryData(
            test=get_object_or_404(TestData, pk=test_id),
            employee_kind=employee_kind,
            subdivision=subdivision,
            faculty=faculty,
            course=course,
        )
        new_questionary_data.save()

        current_test = get_object_or_404(TestData, pk=test_id)
        for question in current_test.question_set.all():
            if question.question_type == MULTIPLE:
                for i in range(question.answer_set.all().count()):
                    if 'question_' + str(question.id) + '_checkbox_' + str(i) in request.POST:
                        answer = get_object_or_404(Answer, pk=request.POST[
                            'question_' + str(question.id) + '_checkbox_' + str(i)])
                        new_result = TestResult.objects.create(
                            questionary_data=new_questionary_data,
                            question=question,
                            answer=answer
                        )
                        if answer.has_extra_data:
                            if 'question_' + str(question.id) + '_checkbox_' + str(i) + '_extra_input' in request.POST:
                                new_result.extra_data = request.POST[
                                    'question_' + str(question.id) + '_checkbox_' + str(i) + '_extra_input']
                                new_result.save()

            elif question.question_type == SINGLE:
                if 'question_' + str(question.id) + '_radio' in request.POST:
                    answer = get_object_or_404(Answer, pk=request.POST[
                        'question_' + str(question.id) + '_radio'])
                    new_result = TestResult.objects.create(
                        questionary_data=new_questionary_data,
                        question=question,
                        answer=answer
                    )

                    if answer.has_extra_data:
                        if 'question_' + str(question.id) + '_radio_extra_input' in request.POST:
                            new_result.extra_data = request.POST['question_' + str(question.id) + '_radio_extra_input']
                            new_result.save()

            elif question.question_type == TEXT:
                if 'question_' + str(question.id) + '_text' in request.POST:
                    new_test_result = TestResult(
                        questionary_data=new_questionary_data,
                        question=question,
                        answer_text=request.POST['question_' + str(question.id) + '_text']
                    )
                    new_test_result.save()
            else:
                pass
        return HttpResponseRedirect(reverse('test_data:success_page'))
    else:
        if request.user_agent.browser.family == 'IE':
            return HttpResponse("Ваш браузер не поддерживается")
        else:

            current_test = get_object_or_404(TestData, pk=test_id)
            return render(request, 'test_data/test_running.html',
                          {
                              'current_test': current_test,
                              'employee_kinds': EmployeeKind.objects.all(),
                              'subdivision_list': Subdivision.objects.all(),
                              'faculties_list': Faculty.objects.all(),
                              'courses_list': Course.objects.all(),
                          })


def success_page(request):
    return render(request, 'test_data/success_page.html')


def dashboard_main(request):
    all_tests_list = TestData.objects.all()
    return render(request, 'test_data/dashboard/dashboard_main.html', {
        'all_tests_list': all_tests_list,
    })


def dashboard_test_result(request, test_id):
    current_test = get_object_or_404(TestData, pk=test_id)
    question_set = current_test.question_set.filter(question_type__in=[SINGLE, MULTIPLE])
    faculties_list = Faculty.objects.all()
    courses_list = Course.objects.all()
    subdivision_list = Subdivision.objects.all()

    cadet_results = TestResult.objects.filter(questionary_data__employee_kind_id=EMPLOYEE_CADET_ID)
    pps_results = TestResult.objects.filter(questionary_data__employee_kind_id=EMPLOYEE_PPS_ID)

    cadet_results_dict = {}
    cadet_results_courses_dict = {}
    pps_results_dict = {}

    for question in question_set:
        answer_res_dict = {}
        for answer in question.answer_set.all():
            faculty_res_dict = {}
            for faculty in faculties_list:
                faculty_res_dict[str(faculty.id)] = cadet_results.filter(questionary_data__faculty=faculty,
                                                                         question=question, answer=answer).count()
            faculty_res_dict['all'] = cadet_results.filter(questionary_data__faculty__in=faculties_list,
                                                           question=question, answer=answer).count()
            answer_res_dict[str(answer.id)] = faculty_res_dict
        cadet_results_dict[str(question.id)] = answer_res_dict

    for question in current_test.question_set.all():
        answer_res_dict = {}
        for answer in question.answer_set.all():
            course_res_dict = {}
            for course in courses_list:
                course_res_dict[str(course.id)] = cadet_results.filter(questionary_data__course=course,
                                                                       question=question, answer=answer).count()
            course_res_dict['all'] = cadet_results.filter(questionary_data__course__in=courses_list,
                                                          question=question, answer=answer).count()
            answer_res_dict[str(answer.id)] = course_res_dict
        cadet_results_courses_dict[str(question.id)] = answer_res_dict

    for question in current_test.question_set.all():
        answer_res_dict = {}
        for answer in question.answer_set.all():
            subdivision_res_dict = {}
            for subdivision in subdivision_list:
                subdivision_res_dict[str(subdivision.id)] = pps_results.filter(
                    questionary_data__subdivision=subdivision,
                    question=question, answer=answer).count()
            subdivision_res_dict['all'] = pps_results.filter(questionary_data__subdivision__in=subdivision_list,
                                                             question=question, answer=answer).count()
            answer_res_dict[str(answer.id)] = subdivision_res_dict
        pps_results_dict[str(question.id)] = answer_res_dict

    return render(request, 'test_data/dashboard/dashboard_test_result.html', {
        'cadet_results_dict': cadet_results_dict,
        'cadet_results_courses_dict': cadet_results_courses_dict,
        'pps_results_dict': pps_results_dict,
        'current_test': current_test,
        'question_set': question_set,
        'faculties_list': faculties_list,
        'courses_list': courses_list,
        'subdivision_list': subdivision_list,
        'cadet_results_count': QuestionaryData.objects.filter(employee_kind=EMPLOYEE_CADET_ID, test_id=test_id).count(),
        'pps_results_count': QuestionaryData.objects.filter(employee_kind=EMPLOYEE_PPS_ID, test_id=test_id).count(),
        'all_results_count': QuestionaryData.objects.filter(test_id=test_id).count(),
    })


def dashboard_test_charts(request, test_id):
    return render(request, 'test_data/dashboard/dashboard_test_charts.html')


def dashboard_test_full(request, test_id):
    questionary_list = QuestionaryData.objects.all()
    current_test = get_object_or_404(TestData, pk=test_id)
    question_list = current_test.question_set.all()
    return render(request, 'test_data/dashboard/dashboard_test_full.html', {
        'questionary_list': questionary_list,
        'current_test': current_test,
        'question_list': question_list,
    })

test_data/templates/test_data/dashboard/dashboard_main.html
{% extends 'base.html' %}


{% block title %}Панель управления{% endblock %}

{% block content %}
    <div class="container">
        <h1>Панель управления</h1>

        <h3>Список тестов</h3>
        <ul class="list-group">
            {% if all_tests_list %}
                {% for test in all_tests_list %}
                    <li class="list-group-item"><a href="{% url 'test_data:dashboard_test_result' test.id %}"
                                                   class="link-secondary">{{ test.test_name }}(проценты)</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'test_data:dashboard_test_full' test.id %}"
                                                   class="link-secondary">{{ test.test_name }} (полная раскладка)</a><br>
                    </li>
                {% endfor %}
            {% else %}
                <h5>Список пуст</h5>
            {% endif %}
        </ul>

        <div>
        </div>
    </div>

{% endblock %}

test_data/templates/test_data/dashboard/dashboard_test_charts.html
<html>
<head>
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

        // Load the Visualization API and the corechart package.
        google.charts.load('current', {packages: ['corechart', 'bar']});
google.charts.setOnLoadCallback(drawBasic);

function drawBasic() {

     google.charts.load('current', {packages: ['corechart', 'bar']});
google.charts.setOnLoadCallback(drawBasic);

function drawBasic() {

      var data = google.visualization.arrayToDataTable([
        ['City', '2011 Population',],
        ['New York City, NY', 8175000],
        ['Los Angeles, CA', 3792000],
        ['Chicago, IL', 2695000],
        ['Houston, TX', 2099000],
        ['Philadelphia, PA', 1526000]
      ]);

      var options = {
        title: 'Population of Largest U.S. Cities',
        chartArea: {width: '50%'},
        hAxis: {
          title: 'Total Population',
          minValue: 0
        },
        vAxis: {
          title: 'City'
        }
      };

      var chart = new google.visualization.BarChart(document.getElementById('chart_div'));

      chart.draw(data, options);
    }
    }
    </script>
</head>

<body>
<!--Div that will hold the pie chart-->
<div id="chart_div"></div>
</body>
</html>

test_data/templates/test_data/dashboard/dashboard_test_full.html
{% extends 'base.html' %}

{% load dict_tags %}

{% block title %}Результаты теста - {{ current_test.test_name }}{% endblock %}
{% block content %}


    <div class="container-fluid p-3" style="background-color: white;">

        <table class="table">
            <thead>
            <tr>
                <th></th>
                {% for question in question_list %}
                    <th scope="col">{{ question.question_text }}</th>
                {% endfor %}

            </tr>

            </thead>
            <tbody>
            {% for questionary in questionary_list %}
                <tr>
                    <td>{{ questionary.employee_kind }}</td>
                    <td>1</td>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                </tr>
            {% endfor %}


            </tbody>
        </table>
    </div>

{% endblock %}

{% block js %}{% endblock %}

test_data/templates/test_data/dashboard/dashboard_test_result.html
{% extends 'base.html' %}

{% load dict_tags %}

{% block title %}Результаты теста - {{ current_test.test_name }}{% endblock %}
{% block content %}
    <div class="container p-3" style="background-color: white;">
        <div class="alert alert-success" role="alert">
            <h1 class="mb-3">{{ current_test.test_name }}</h1>
            <h5>Всего пройдено тестов - {{ all_results_count }}</h5>
            <h5>Из них: курсанты - {{ cadet_results_count }}, постоянный состав - {{ pps_results_count }}</h5>
        </div>
        <div class="alert alert-primary" role="alert">
            <h2>Курсанты</h2>
        </div>
        <h3>Распределение по факультетам</h3>
        <div>
            <table class="table table-hover table-bordered">
                <thead class="table-warning">
                <tr>
                    <th></th>
                    {% for faculty in faculties_list %}
                        <th scope="col" class="text-center">{{ faculty.faculty_name }}</th>
                    {% endfor %}
                    <th class="text-center">Всего по факультетам</th>
                </tr>
                </thead>
                <tbody>
                {% for question in question_set %}
                    {% with quest_dict=cadet_results_dict|get_sub_dict:question.id %}
                        <tr>
                            <td colspan="{{ faculties_list.count|add:"2" }}">{{ question.question_text }}</td>
                            {% for answer in question.answer_set.all %}
                                {% with answer_dict=quest_dict|get_sub_dict:answer.id %}
                                    <tr>
                                        <td>{{ answer }}</td>
                                        {% for faculty in faculties_list %}
                                            <td class="text-center">{{ answer_dict|get_value_form_dict:faculty.id }}</td>
                                        {% endfor %}
                                        <td class="text-center">{{ answer_dict|get_value_form_dict:"all" }}</td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                        </tr>
                    {% endwith %}
                {% endfor %}
                </tbody>
            </table>
        </div>
        <br>
        <h3>Распределение по курсам</h3>
        <div>
            <table class="table table-hover table-bordered">
                <thead class="table-warning">
                <tr>
                    <th></th>
                    {% for course in courses_list %}
                        <th scope="col" class="text-center">{{ course.course_name }}</th>
                    {% endfor %}
                    <th class="text-center">Всего по курсам</th>
                </tr>
                </thead>
                <tbody>
                {% for question in question_set %}
                    {% with quest_dict=cadet_results_courses_dict|get_sub_dict:question.id %}
                        <tr>
                            <td colspan="{{ courses_list.count|add:"2" }}">{{ question.question_text }}</td>
                            {% for answer in question.answer_set.all %}
                                {% with answer_dict=quest_dict|get_sub_dict:answer.id %}
                                    <tr>
                                        <td>{{ answer }}</td>
                                        {% for course in courses_list %}
                                            <td class="text-center">{{ answer_dict|get_value_form_dict:course.id }}</td>
                                        {% endfor %}
                                        <td class="text-center">{{ answer_dict|get_value_form_dict:"all" }}</td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                        </tr>
                    {% endwith %}
                {% endfor %}
                </tbody>
            </table>
        </div>
        <br>

        <div class="alert alert-primary" role="alert">
            <h2>Переменный состав</h2>
        </div>

        <h3>Распределение по подразделениям</h3>
        <div>
            <table class="table table-hover table-bordered">
                <thead class="table-warning">
                <tr>
                    <th></th>
                    {% for subdivision in subdivision_list %}
                        <th scope="col" class="text-center">{{ subdivision.subdivision_name }}</th>
                    {% endfor %}
                    <th class="text-center">Всего по подразделениям</th>
                </tr>
                </thead>
                <tbody>
                {% for question in question_set %}
                    {% with quest_dict=pps_results_dict|get_sub_dict:question.id %}
                        <tr>
                            <td colspan="{{ subdivision_list.count|add:"2" }}">{{ question.question_text }}</td>
                            {% for answer in question.answer_set.all %}
                                {% with answer_dict=quest_dict|get_sub_dict:answer.id %}
                                    <tr>
                                        <td>{{ answer }}</td>
                                        {% for subdivision in subdivision_list %}
                                            <td class="text-center">{{ answer_dict|get_value_form_dict:subdivision.id }}</td>
                                        {% endfor %}
                                        <td class="text-center">{{ answer_dict|get_value_form_dict:"all" }}</td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                        </tr>
                    {% endwith %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>
    setInterval(() => window.location.reload(), 20000);
    </script>
{% endblock %}