oir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tests/', include('test_data.urls')),
    path('', RedirectView.as_view(url='/tests'), name='go-to-tests'),
]

test_data/urls.py
from django.urls import path
from . import views

app_name = 'test_data'

urlpatterns = [
    path('', views.tests_list, name='test_list'),
    path('running/<test_id>', views.tests_running, name='test_running'),
    path('success', views.success_page, name='success_page'),
    path('dashboard', views.dashboard_main, name='dashboard_main'),
    path('dashboard/tests/<test_id>', views.dashboard_test_result, name='dashboard_test_result'),
    path('dashboard/tests/<test_id>/charts', views.dashboard_test_charts, name='dashboard_test_charts'),
    path('dashboard/tests/<test_id>/full', views.dashboard_test_full, name='dashboard_test_full'),
]

test_data/models.py
from django.db import models


SINGLE = 1
MULTIPLE = 2
TEXT = 3

QUESTION_TYPE_CHOICES = (
    (SINGLE, 'Single (radio)'),
    (MULTIPLE, 'Multiple (checkbox)'),
    (TEXT, 'Text field'),
)


class EmployeeKind(models.Model):
    employee_kind = models.CharField(verbose_name="Вид сотрудника", max_length=255)

    def __str__(self):
        return self.employee_kind

    class Meta:
        ordering = ('id',)
        verbose_name = 'EmployeeKind'
        verbose_name_plural = 'EmployeeKinds'


class Subdivision(models.Model):
    subdivision_name = models.CharField(verbose_name="Название подразделения", max_length=255)

    def __str__(self):
        return self.subdivision_name

    class Meta:
        ordering = ('id',)
        verbose_name = 'Subdivision'
        verbose_name_plural = 'Subdivisions'


class Faculty(models.Model):
    faculty_name = models.CharField(verbose_name="Название факультета", max_length=255)

    def __str__(self):
        return self.faculty_name

    class Meta:
        ordering = ('id',)
        verbose_name = 'Faculty'
        verbose_name_plural = 'Faculties'


class Course(models.Model):
    course_name = models.CharField(verbose_name="Курс", max_length=255)

    def __str__(self):
        return self.course_name

    class Meta:
        ordering = ('id',)
        verbose_name = 'Course'
        verbose_name_plural = 'Courses'


class TestData(models.Model):
    test_name = models.CharField(verbose_name="Название теста", max_length=255)
    extra_data = models.TextField(verbose_name="Дополнительная информация", blank=True, null=True)
    data_created = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)

    def __str__(self):
        return self.test_name

    class Meta:
        ordering = ('id',)
        verbose_name = 'TestData'
        verbose_name_plural = '1 TestsData'


class QuestionaryData(models.Model):
    test = models.ForeignKey(TestData, verbose_name="Тест", on_delete=models.CASCADE, blank=True, null=True)
    employee_kind = models.ForeignKey(EmployeeKind, verbose_name="Тип сотрудника", on_delete=models.CASCADE)
    subdivision = models.ForeignKey(Subdivision, on_delete=models.CASCADE, verbose_name="Подразделение", blank=True,
                                    null=True)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE, verbose_name="Факультет", blank=True,
                                null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="Курс", blank=True,
                               null=True)

    def __str__(self):
        return self.employee_kind.employee_kind

    class Meta:
        ordering = ('id',)
        verbose_name = 'QuestionaryData'
        verbose_name_plural = 'QuestionaryData'


class Question(models.Model):
    question_type = models.IntegerField(verbose_name="Тип вопроса", choices=QUESTION_TYPE_CHOICES, default=SINGLE)
    test_data = models.ForeignKey(TestData, on_delete=models.CASCADE, verbose_name="Тест")
    question_text = models.CharField(verbose_name="Текст вопроса", max_length=255)
    index_number = models.IntegerField(verbose_name="Порядковый номер вопроса", blank=True, null=True)

    def __str__(self):
        return self.question_text + ' ' + str(self.question_type)

    class Meta:
        ordering = ('index_number',)
        verbose_name = 'Question'
        verbose_name_plural = '2 Questions'


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name="Вопрос")
    answer_text = models.CharField(verbose_name="Текст ответа", max_length=255)
    has_extra_data = models.BooleanField(verbose_name="Имеет дополнительную информацию", default=False)
    index_number = models.IntegerField(verbose_name="Порядковый номер ответа", blank=True, null=True)

    def __str__(self):
        return self.answer_text

    class Meta:
        ordering = ('id',)
        verbose_name = 'Answer'
        verbose_name_plural = '3 Answers'


class TestResult(models.Model):
    questionary_data = models.ForeignKey(QuestionaryData, on_delete=models.CASCADE, verbose_name="Данные анкеты")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name="Вопрос")
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, verbose_name="Ответ", blank=True, null=True)
    answer_text = models.TextField(verbose_name="Ответ (текстовый)", blank=True, null=True)
    extra_data = models.TextField(verbose_name="Дополнительная информация к ответу", blank=True, null=True)

    def __str__(self):
        return self.questionary_data.employee_kind.employee_kind + ' ' + self.question.question_text

    class Meta:
        ordering = ('id',)
        verbose_name = 'TestResult'
        verbose_name_plural = '4 TestResults'

test_data/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from .models import TestData, Subdivision, Faculty, Course, QuestionaryData, EmployeeKind, TestResult, Answer
from .models import SINGLE, MULTIPLE, TEXT
from django.db import transaction
from django.http import HttpResponse

EMPLOYEE_CADET_ID = 1
EMPLOYEE_PPS_ID = 2


def tests_list(request):
    if request.user_agent.browser.family == 'IE':
        return HttpResponse("Ваш браузер не поддерживается")
    else:
        all_tests_list = TestData.objects.all()
        return render(request, 'test_data/test_list.html', {'all_tests_list': all_tests_list})


@transaction.atomic
def tests_running(request, test_id):
    if request.method == "POST":
        employee_kind = get_object_or_404(EmployeeKind, pk=request.POST['employee_kind'])
        subdivision = get_object_or_404(Subdivision,
                                        pk=request.POST['subdivision']) if 'subdivision' in request.POST and \
                                                                           request.POST['subdivision'] != '' else None
        faculty = get_object_or_404(Faculty, pk=request.POST['faculty']) if 'faculty' in request.POST and request.POST[
            'faculty'] != '' else None
        course = get_object_or_404(Course, pk=request.POST['course']) if 'course' in request.POST and request.POST[
            'course'] != '' else None

        new_questionary_data = QuestionaryData(
            test=get_object_or_404(TestData, pk=test_id),
            employee_kind=employee_kind,
            subdivision=subdivision,
            faculty=faculty,
            course=course,
        )
        new_questionary_data.save()

        current_test = get_object_or_404(TestData, pk=test_id)
        for question in current_test.question_set.all():
            if question.question_type == MULTIPLE:
                for i in range(question.answer_set.all().count()):
                    if 'question_' + str(question.id) + '_checkbox_' + str(i) in request.POST:
                        answer = get_object_or_404(Answer, pk=request.POST[
                            'question_' + str(question.id) + '_checkbox_' + str(i)])
                        new_result = TestResult.objects.create(
                            questionary_data=new_questionary_data,
                            question=question,
                            answer=answer
                        )
                        if answer.has_extra_data:
                            if 'question_' + str(question.id) + '_checkbox_' + str(i) + '_extra_input' in request.POST:
                                new_result.extra_data = request.POST[
                                    'question_' + str(question.id) + '_checkbox_' + str(i) + '_extra_input']
                                new_result.save()

            elif question.question_type == SINGLE:
                if 'question_' + str(question.id) + '_radio' in request.POST:
                    answer = get_object_or_404(Answer, pk=request.POST[
                        'question_' + str(question.id) + '_radio'])
                    new_result = TestResult.objects.create(
                        questionary_data=new_questionary_data,
                        question=question,
                        answer=answer
                    )

                    if answer.has_extra_data:
                        if 'question_' + str(question.id) + '_radio_extra_input' in request.POST:
                            new_result.extra_data = request.POST['question_' + str(question.id) + '_radio_extra_input']
                            new_result.save()

            elif question.question_type == TEXT:
                if 'question_' + str(question.id) + '_text' in request.POST:
                    new_test_result = TestResult(
                        questionary_data=new_questionary_data,
                        question=question,
                        answer_text=request.POST['question_' + str(question.id) + '_text']
                    )
                    new_test_result.save()
            else:
                pass
        return HttpResponseRedirect(reverse('test_data:success_page'))
    else:
        if request.user_agent.browser.family == 'IE':
            return HttpResponse("Ваш браузер не поддерживается")
        else:

            current_test = get_object_or_404(TestData, pk=test_id)
            return render(request, 'test_data/test_running.html',
                          {
                              'current_test': current_test,
                              'employee_kinds': EmployeeKind.objects.all(),
                              'subdivision_list': Subdivision.objects.all(),
                              'faculties_list': Faculty.objects.all(),
                              'courses_list': Course.objects.all(),
                          })


def success_page(request):
    return render(request, 'test_data/success_page.html')


def dashboard_main(request):
    all_tests_list = TestData.objects.all()
    return render(request, 'test_data/dashboard/dashboard_main.html', {
        'all_tests_list': all_tests_list,
    })


def dashboard_test_result(request, test_id):
    current_test = get_object_or_404(TestData, pk=test_id)
    question_set = current_test.question_set.filter(question_type__in=[SINGLE, MULTIPLE])
    faculties_list = Faculty.objects.all()
    courses_list = Course.objects.all()
    subdivision_list = Subdivision.objects.all()

    cadet_results = TestResult.objects.filter(questionary_data__employee_kind_id=EMPLOYEE_CADET_ID)
    pps_results = TestResult.objects.filter(questionary_data__employee_kind_id=EMPLOYEE_PPS_ID)

    cadet_results_dict = {}
    cadet_results_courses_dict = {}
    pps_results_dict = {}

    for question in question_set:
        answer_res_dict = {}
        for answer in question.answer_set.all():
            faculty_res_dict = {}
            for faculty in faculties_list:
                faculty_res_dict[str(faculty.id)] = cadet_results.filter(questionary_data__faculty=faculty,
                                                                         question=question, answer=answer).count()
            faculty_res_dict['all'] = cadet_results.filter(questionary_data__faculty__in=faculties_list,
                                                           question=question, answer=answer).count()
            answer_res_dict[str(answer.id)] = faculty_res_dict
        cadet_results_dict[str(question.id)] = answer_res_dict

    for question in current_test.question_set.all():
        answer_res_dict = {}
        for answer in question.answer_set.all():
            course_res_dict = {}
            for course in courses_list:
                course_res_dict[str(course.id)] = cadet_results.filter(questionary_data__course=course,
                                                                       question=question, answer=answer).count()
            course_res_dict['all'] = cadet_results.filter(questionary_data__course__in=courses_list,
                                                          question=question, answer=answer).count()
            answer_res_dict[str(answer.id)] = course_res_dict
        cadet_results_courses_dict[str(question.id)] = answer_res_dict

    for question in current_test.question_set.all():
        answer_res_dict = {}
        for answer in question.answer_set.all():
            subdivision_res_dict = {}
            for subdivision in subdivision_list:
                subdivision_res_dict[str(subdivision.id)] = pps_results.filter(
                    questionary_data__subdivision=subdivision,
                    question=question, answer=answer).count()
            subdivision_res_dict['all'] = pps_results.filter(questionary_data__subdivision__in=subdivision_list,
                                                             question=question, answer=answer).count()
            answer_res_dict[str(answer.id)] = subdivision_res_dict
        pps_results_dict[str(question.id)] = answer_res_dict

    return render(request, 'test_data/dashboard/dashboard_test_result.html', {
        'cadet_results_dict': cadet_results_dict,
        'cadet_results_courses_dict': cadet_results_courses_dict,
        'pps_results_dict': pps_results_dict,
        'current_test': current_test,
        'question_set': question_set,
        'faculties_list': faculties_list,
        'courses_list': courses_list,
        'subdivision_list': subdivision_list,
        'cadet_results_count': QuestionaryData.objects.filter(employee_kind=EMPLOYEE_CADET_ID, test_id=test_id).count(),
        'pps_results_count': QuestionaryData.objects.filter(employee_kind=EMPLOYEE_PPS_ID, test_id=test_id).count(),
        'all_results_count': QuestionaryData.objects.filter(test_id=test_id).count(),
    })


def dashboard_test_charts(request, test_id):
    return render(request, 'test_data/dashboard/dashboard_test_charts.html')


def dashboard_test_full(request, test_id):
    questionary_list = QuestionaryData.objects.all()
    current_test = get_object_or_404(TestData, pk=test_id)
    question_list = current_test.question_set.all()
    return render(request, 'test_data/dashboard/dashboard_test_full.html', {
        'questionary_list': questionary_list,
        'current_test': current_test,
        'question_list': question_list,
    })

test_data/templates/test_data/success_page.html
{% extends 'base.html' %}


{% block title %}Анкетирование{% endblock %}

{% block content %}
    <div class="container">

        <div style="background-color: white;height: 150px;" class="p-3 my-3 rounded-3 d-flex justify-content-center align-items-center flex-column">
            <h1>Спасибо за анкетирование!</h1>
            <a href="/" class="link-secondary"><h3>Вернуться на главную</h3></a>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        setTimeout(() => window.location.href = '/', 5000);
    </script>
{% endblock %}

test_data/templates/test_data/test_list.html
{% extends 'base.html' %}


{% block title %}Список тестов{% endblock %}

{% block content %}
    <div class="container">

        <div style="background-color: #6f42c1; height: 150px;"
             class="d-flex align-items-center p-3 my-3 rounded-3 text-white">
            <img src="" alt="">
            <div>
                <h1>Академия МВД Республики Беларусь</h1>
                <small>Отдел идеологической работы</small>
            </div>
        </div>


        <ul class="list-group">
            {% if all_tests_list %}
                {% for test in all_tests_list %}
                    <li class="list-group-item mb-3"><a href="{% url 'test_data:test_running' test.id %}"
                                                   class="link-secondary">{{ test.test_name }}</a><br>
                    </li>
                {% endfor %}
            {% else %}
                <h5>Список пуст</h5>
            {% endif %}
        </ul>
    </div>

{% endblock %}

test_data/templates/test_data/test_running.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ current_test.test_name }}{% endblock %}

{% block content %}
    <div style="background-color: lightgray; height: 100vh">
        <div class="container" style="background-color: lightgray;">

            <div style="background-color: #6f42c1; height: 150px;"
                 class="d-flex align-items-center p-3 my-3 rounded-3 text-white">
                <img src="" alt="">
                <div>
                    <h1>Академия МВД Республики Беларусь</h1>
                    <small>Отдел идеологической работы</small>
                </div>
            </div>


            <div class="mt-3">
                <div style="background-color: white" class="rounded-3 p-3 mb-3">
                    <h1 class="text-center">{{ current_test.test_name }}</h1>
                    <p style="text-indent: 1.5rem; text-align: justify;font-size: 1.2rem;">{{ current_test.extra_data }}</p>
                </div>

                <form action="{% url 'test_data:test_running' current_test.id %}" method="POST">{% csrf_token %}

                    <div style="background-color: white" class="p-3 mb-3 rounded-3">
                        <div class="mb-3">
                            <label class="form-label"><h5>Выберите категорию сотрудника</h5></label>
                            <select class="form-select" aria-label="Default select example" name="employee_kind"
                                    id="employee_kind_id"
                                    required>
                                <option selected value="">----------</option>
                                {% for employee_kind in employee_kinds %}
                                    <option value="{{ employee_kind.id }}">{{ employee_kind.employee_kind }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>


                    <div style="background-color: white; display: none;" class="p-3 mb-3 rounded-3"
                         id="subdivision_div_id">
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label"><h5>Выберите подразделение</h5></label>
                            <select class="form-select" aria-label="Default select example" name="subdivision"
                                    id="subdivision_id">
                                <option selected value="">----------</option>
                                {% for subdivision in subdivision_list %}
                                    <option value="{{ subdivision.id }}">{{ subdivision.subdivision_name }}</option>
                                {% endfor %}
                            </select>
                        </div>

                    </div>


                    <div style="background-color: white; display: none;" class="p-3 mb-3 rounded-3"
                         id="cadet_data_div_id">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="exampleInputEmail1" class="form-label"><h5>Выберите факультет</h5>
                                    </label>
                                    <select class="form-select" aria-label="Default select example" name="faculty"
                                            id="faculty_id">
                                        <option selected value="">----------</option>
                                        {% for faculty in faculties_list %}
                                            <option value="{{ faculty.id }}">{{ faculty.faculty_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="exampleInputEmail1" class="form-label"><h5>Выберите курс</h5></label>
                                    <select class="form-select" aria-label="Default select example" name="course"
                                            id="course_id">
                                        <option selected value="">----------</option>
                                        {% for course in courses_list %}
                                            <option value="{{ course.id }}">{{ course.course_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% for question in current_test.question_set.all %}
                        <div style="background-color: white" class="p-3 mb-3 rounded-3">
                            <h5>{{ question.question_text }}</h5>
                            {% if question.question_type == 1 %}
                                {% for answer in question.answer_set.all %}
                                    <div class="form-check my-2">
                                        {% if answer.has_extra_data %}
                                            <input class="form-check-input answer_radio radio_with_extra_data"
                                                   type="radio"
                                                   name="question_{{ question.id }}_radio" value="{{ answer.id }}"
                                                   required>
                                        {% else %}
                                            <input class="form-check-input answer_radio" type="radio"
                                                   name="question_{{ question.id }}_radio" value="{{ answer.id }}"
                                                   required>
                                        {% endif %}
                                        <label class="form-check-label">
                                            {{ answer }}
                                        </label>
                                    </div>
                                    {% if answer.has_extra_data %}
                                        <div class="answer_extra_data_div_class"
                                             id="question_{{ question.id }}_radio_extra_div_id"
                                             style="display: none">
                                            <input type="text" class="form-control"
                                                   id="question_{{ question.id }}_radio_extra_input_id"
                                                   name="question_{{ question.id }}_radio_extra_input"
                                                   disabled>
                                        </div>
                                    {% endif %}


                                {% endfor %}
                            {% elif question.question_type == 2 %}
                                {% for answer in question.answer_set.all %}
                                    <div class="form-check my-2">
                                        {% if answer.has_extra_data %}
                                            <input class="form-check-input check_with_extra_data" type="checkbox"
                                                   name="question_{{ question.id }}_checkbox_{{ forloop.counter0 }}"
                                                   value="{{ answer.id }}">
                                        {% else %}
                                            <input class="form-check-input" type="checkbox"
                                                   name="question_{{ question.id }}_checkbox_{{ forloop.counter0 }}"
                                                   value="{{ answer.id }}">
                                        {% endif %}

                                        <label class="form-check-label" for="flexCheckDefault">
                                            {{ answer }}
                                        </label>
                                    </div>
                                    {% if answer.has_extra_data %}
                                        <div class="answer_extra_data_div_class"
                                             id="question_{{ question.id }}_checkbox_{{ forloop.counter0 }}_extra_div_id"
                                             style="display: none">
                                            <input type="text" class="form-control"
                                                   id="question_{{ question.id }}_checkbox_{{ forloop.counter0 }}_extra_input_id"
                                                   name="question_{{ question.id }}_checkbox_{{ forloop.counter0 }}_extra_input"
                                                   disabled>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            {% elif question.question_type == 3 %}
                                <input type="text" class="form-control"
                                                   id="question_{{ question.id }}_text_id"
                                                   name="question_{{ question.id }}_text" required>
                            {% endif %}

                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary mb-3"
                            style="background-color: #6f42c1; border-color: #6f42c1">Отравить ответы
                    </button>
                </form>
            </div>

        </div>
    </div>


{% endblock %}

{% block js %}
    <script src="{% static 'test_data/js/test_running_UI.js' %}"></script>
{% endblock %}